run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
  settings:
    govet:
      enable-all: true

issues:
  exclusions:
    rules:
      - linters:
          - errcheck
        text: "G104"
        path: "_test\\.go"