version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - shadow
    - gofmt
    - goimports

linters_settings:
  govet:
    enable_all: true

issues:
  exclude_rules:
    - path: _test\.go$
      linters:
        - errcheck
      text: "Error return value"